### ISSUE TITLE
help

### ISSUE THREAD

**Issue by funnymonkejuice** [Sharrnah/whispering#8] opened 2023-03-17 17:10 UTC
i tried to use it but its not working and every time I open it it asks for an update

**Comment by Sharrnah** [comment] 2023-03-18 20:24
If you are using the UI, if you are starting it for the first time, it will ask for an update of the Python Backend, because it does not have it yet. (And if you have downloaded it manually, it does not know about it).

So to use it, you need to confirm the update question and wait for the download to finish.
After that, you can create a Profile with settings that fit your PC (you are free to ask about help here maybe in a seperate issue.)
If you scroll down at the profile window, click on "Save and Load Profile".

It will start the Python Backend in the background, The Backend will download some AI models depending on the settings you choose, so this might take some time again unfortunately. But here you can close the waiting window and see in _Advanced -> Log_ what it is currently doing.

I hope that helps a bit.

**Comment by Sharrnah** [comment] 2023-03-19 17:17
duplicate of https://github.com/Sharrnah/whispering-ui/issues/3

**Closed by Sharrnah** 2023-03-19 17:17 UTC
